[package]
name = "client"
version = "0.1.0"
# src_folder = "src"
# include_folder = "include"
# additional_compiler_flags = [...]
additional_linker_flags = ["-lraylib"]
# enable_pthread_library = false
enable_math_library = true
# disable_std_library = false
